FROM nginx:latest

RUN apt-get update && apt-get install software-properties-common -y
RUN apt-get install -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /root

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]