version: '2'
services:
  webapp1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meme-webapp-1
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
#      - elasticsearch
  webapp2:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: meme-webapp-2
      ports:
        - "3001:3000"
      depends_on:
        - postgres
        - redis
  #      - elasticsearch
  webapp3:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: meme-webapp-3
      ports:
        - "3002:3000"
      depends_on:
        - postgres
        - redis
  #      - elasticsearch
#  elasticsearch:
#    build:
#      context: .
#      dockerfile: Dockerfile.es-ko
#    image: wsdg4/elasticsearch
#    container_name: meme-es
  postgres:
    image: postgres
    container_name: meme-db
  redis:
    image: redis
    container_name: meme-redis
  nginx:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      hostname: nginx
      ports:
        - "80:80"
        - "443:443"
      links:
        - webapp1
        - webapp2
        - webapp3