FROM nginx:latest

RUN apt-get update && apt-get install software-properties-common -y
RUN apt-get install -y \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD nginx.conf /etc/nginx/conf.d/default.conf
CMD sed -i '$ a worker_processes 1;' /etc/nginx/nginx.conf
CMD sed -i '$ a worker_connections 1024;' /etc/nginx/nginx.conf

COPY ./public webapp/public
WORKDIR webapp

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
